markdown: rdiscount
pygments: true
lsi: true # Enabled to create better "related posts" list. Will increase compile time
exclude: ['sass/', 'Rakefile', 'config.rb']

# Local
#static_path: /Users/bjtitus/Dropbox/Projects/blog/_site

# Local Python server: python -m SimpleHTTPServer [port]
#static_path: 

# LIVE
static_path: http://s.half-news.com/blog/templates