# Site settings
title: Brandon Titus
email: brandon@titus.io
description: > # this means to ignore newlines until "baseurl:"
  A place for opinions, reviews, essays, and inherent biases.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://titus.io" # the base hostname & protocol for your site
twitter_username: bjtitus
github_username:  bjtitus
stackoverflow_username: bjtitus
stackoverflow_userid: 72319

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "underline", "strikethrough"]

collections:
  photosets:
    output: true