markdown: rdiscount
pygments: true
lsi: true # Enabled to create better "related posts" list. Will increase compile time
exclude: ['sass/', 'Rakefile', 'config.rb']

# Local
#static_path: /Users/bjtitus/Dropbox/Projects/blog/_site

# LIVE
static_path: http://files.bjtitus.net/blog/templates