--- 
lsi: true
exclude: 
- sass/
- Rakefile
- config.rb
- local_config.rb
- parent_config.rb
markdown: rdiscount
pygments: true
combined_css_name: combined-1313803558.min.css
static_path: /
static_template: /
