--- 
lsi: true
exclude: 
- sass/
- Rakefile
- config.rb
- local_config.rb
- parent_config.rb
markdown: rdiscount
pygments: true
combined_css_name: combined-1313805625.min.css
static_path: http://s.half-news.com/blog/
static_template: http://s.half-news.com/blog/templates/
