---
lsi: true
exclude:
- sass/
- Rakefile
- config.rb
- local_config.rb
- parent_config.rb
- remote_config.rb
markdown: rdiscount
pygments: true
combined_css_name: true
static_path: http://s.half-news.com/blog/
static_template: http://s.half-news.com/blog/templates/
prose:
  metadata:
    _posts/articles: ! 'title:  "Title of your article"'
